name = "anyflare"
main = "src/index.ts"
compatibility_date = "2024-11-25"

[assets]
directory = "./public"
binding = "ANYFLARE_ASSETS"
html_handling = "force-trailing-slash"
not_found_handling = "404-page"

